config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :wallets
  resources :projects
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :wallets, through: :project_wallets
  validates_presence_of :pair
  validates_uniqueness_of :pair

  enum status: {
    unchecked: 0,
    active: 1,
    discarded: 10
  }

  scope :active, -> { where.not(status: :discarded) }
  
end

app/models/project_wallet.rb
class ProjectWallet < ApplicationRecord
  belongs_to :project
  belongs_to :wallet
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :projects, through: :project_wallets
  validates_presence_of :address
  validates_uniqueness_of :address

  enum status: {
    unchecked: 0,
    active: 1,
    discarded: 10
  }

  scope :active, -> { where.not(status: :discarded) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
    @wallets = Wallet.active.order(created_at: :desc)
    @projects = Project.active.order(created_at: :desc)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def create
    project = Project.new(params[:project].permit!)
    project.save
    redirect_to root_path
  end

  def update
    project = Project.find(params[:id])
    project.update(params[:project].permit!)
    redirect_to root_path
  end

end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController

  def create
    Wallet.create(params[:wallet].permit!)
    redirect_to root_path
  end

  def update
    wallet = Wallet.find(params[:id])
    wallet.update(params[:wallet].permit!)
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.slim
.flex.flex-wrap.gap-4.text-xl
  .p-2.rounded.bg-slate-950.w-48.border.border-slate-900.shadow
    .mb-3
      .text-sm.font-bold.bg-black.rounded.inline.tracking-wide.py-1.px-2.text-emerald-500 FIND WALLET
    .my-3 = link_to 'dex', 'https://dexscreener.com/?rankBy=trendingScoreH6&order=desc&minLiq=50000&min24HTxns=200&min24HVol=100000', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
  .p-2.rounded.bg-slate-950.w-96.border.border-slate-900.shadow
    .mb-3
      .text-sm.font-bold.bg-black.rounded.inline.tracking-wide.py-1.px-2.text-emerald-500 CHECK PROJECT
    .my-3 = link_to 'twitter score', 'https://twitterscore.io/', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
    .my-3 = link_to 'solscan', 'https://solscan.io/', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
    .my-3 = link_to 'rugcheck', 'https://rugcheck.xyz/', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
    hr.border-slate-700.my-2
    .text-xs.px-1
      div Liquidity must be collateralized
      div Top 10 holders must not own more than 30% of the token

  .p-2.rounded.bg-slate-950.w-48.border.border-slate-900.shadow
    .mb-3
      .text-sm.font-bold.bg-black.rounded.inline.tracking-wide.py-1.px-2.text-emerald-500 TRACK WALLET
    .my-3 = link_to 'cielo', 'https://app.cielo.finance/feed', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
    .my-3
      = link_to 'gmgn', 'https://gmgn.ai/?chain=sol', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
      .text-xs.px-1 PNL and winrate (min 70%)
    = link_to 'RayBot', 'https://t.me/ray_silver_bot', target: :_blank, class: 'bg-slate-800 rounded shadow hover:bg-slate-700 text-slate-500 shadow px-1'
  
.grid.grid-cols-2.gap-4.text-xl.w-full

  .rounded.bg-slate-950.border.border-slate-800.b9rder-2.shadow.p-4
    .text-2xl Wallets
    = form_with model: Wallet.new, class: 'my-6' do |f|
      .flex.gap-3
        = f.text_field :address, placeholder: 'Address', class: 'flex-grow text-lg bg-slate-800 border p-2 rounded border-none', required: true
        = f.submit 'Add', class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-slate-500 hover:cursor-pointer'
      = f.text_area :notes, class: 'flex-grow text-lg bg-slate-800 border p-2 rounded border-none text-xs w-full my-3', placeholder: 'Notes'

    - @wallets.each do |wallet|
      .my-3.grid.grid-cols-6.gap-2.items-center
        .col-span-3 = link_to "...#{wallet.address.last(6)}", "https://app.cielo.finance/profile/#{wallet.address}/pnl/tokens", target: :_blank, class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-slate-500'
        .col-span-2.text-xs.h-10.overflow-auto.hide-scrollbar = wallet.notes
        = link_to '❌', wallet_path(wallet, wallet: {status: :discarded}), method: :patch, class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-center shadow', data: {confirm: 'Are you sure?'}
      - unless wallet == @wallets.last
        hr.border-slate-800

  .rounded.bg-slate-950.border.border-slate-800.b9rder-2.shadow.p-4
    .text-2xl Projects
    = form_with model: Project.new, class: 'flex gap-3 my-6' do |f|
      = f.text_field :name, placeholder: 'Name', class: 'flex-grow text-lg bg-slate-800 border p-2 rounded border-none', required: true
      = f.number_field :pair, placeholder: 'Address', class: 'flex-grow text-lg bg-slate-800 border p-2 rounded border-none', required: true
      = f.submit 'Add', class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-slate-500 hover:cursor-pointer'

    - @projects.each do |project|
      .my-3.grid.grid-cols-6.gap-2
        .col-span-4 = project.name
        = link_to "...#{project.pair.last(6)}", "https://dexscreener.com/solana/#{project.pair}", target: :_blank, class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-center shadow'
        = link_to '❌', project_path(project, project: {status: :discarded}), method: :patch, class: 'bg-slate-800 px-2 rounded shadow hover:bg-slate-700 text-center shadow', data: {confirm: 'Are you sure?'}
      - unless project == @projects.last
        hr.border-slate-800

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>💰</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💰</text></svg>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700;800;900&family=IM+Fell+Great+Primer:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
      
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

  </head>

  <body class='py-10 bg-gradient-to-t from-black to-slate-950 text-slate-400'>
    <div class='flex flex-col items-center gap-16 px-10'>
      <%= yield %>
    </div>
  </body>
</html>